import Footer from "@/components/layout/Footer";
import "./globals.css"; 
import { Inter,  Readex_Pro } from 'next/font/google' // Arabic font

const readexPro = Readex_Pro({
  subsets: ['arabic'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-readex-pro',
});

const inter = Inter({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata = {
    title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children  }) {
  return (

    <html lang="ar" dir="rtl" className={`${inter.variable} ${readexPro.variable}`}>
      <body className="font-readex">
        {children}
        <Footer/>
      </body>
    </html>
  );
}
